/**
 * Emits `lib/api/generated-bot-methods.ts`: one `bot.<method>(...)` wrapper per
 * Bot API method that BotService doesn't hand-own (see manifest SKIP_BOT_METHODS).
 *
 * The shape mirrors the hand-written sugar: REQUIRED args are positional, the
 * OPTIONAL ones go in a trailing `options` object (which also carries the
 * per-call `token`/`signal`). Positional param types are written as indexed
 * access into the method's Options interface (`SendMessageOptions['chat_id']`),
 * so the file only needs to import the method classes + their Options — no Raw
 * types, InputFile, or InputMedia imports, and no cast (positional supplies the
 * required fields, the spread supplies the optional ones).
 *
 * Output is unformatted; the orchestrator runs Prettier so the committed file
 * matches lint-staged.
 */
import { IrField, IrMethod } from './ir';
import { isSkippedBotMethod } from './manifest';

const HEADER = `// GENERATED by tools/codegen — do not edit.
// Run \`npm run generate\` to refresh; \`npm run generate -- --check\` guards staleness.`;

/** Escape a spec description so it can't break out of the JSDoc block. */
function sanitize(text: string): string {
  return (text ?? '').replace(/\*\//g, '*\\/').trim();
}

function jsdoc(method: IrMethod, positional: IrField[]): string {
  const lines: string[] = [];
  const description = sanitize(method.description);
  if (description) {
    lines.push(
      ...description.split('\n').map((line) => ` * ${line}`.trimEnd()),
    );
  }
  for (const field of positional) {
    const fieldDescription = sanitize(field.description).replace(/\s+/g, ' ');
    lines.push(
      ` * @param ${field.name}${
        fieldDescription ? ` ${fieldDescription}` : ''
      }`,
    );
  }
  return lines.length > 0 ? `/**\n${lines.join('\n')}\n */\n` : '';
}

// `callOptions`/`rest` are camelCase so they can't collide with a snake_case
// payload field named `options` (sendPoll) or `payload` (sendInvoice).

/** The trailing controls parameter — omits the positional fields, or is just CallOptions. */
function optionsParam(
  className: string,
  required: IrField[],
  optional: IrField[],
): string {
  if (optional.length === 0) {
    return 'callOptions?: CallOptions';
  }
  if (required.length === 0) {
    return `callOptions?: MethodOptions<${className}Options>`;
  }
  const omit = required.map((field) => `'${field.name}'`).join(' | ');
  return `callOptions?: MethodOptions<Omit<${className}Options, ${omit}>>`;
}

function emitMethod(method: IrMethod): string {
  const { className, name, args } = method;

  // No-arg methods (ApiMethod<null, R>): the whole arg IS the call controls.
  if (args.length === 0) {
    return `${jsdoc(method, [])}${name}(callOptions?: CallOptions) {
  return this.call(new ${className}(), callOptions);
}`;
  }

  const required = args.filter((arg) => !arg.optional);
  const optional = args.filter((arg) => arg.optional);
  const positional = required.map(
    (field) => `${field.name}: ${className}Options['${field.name}']`,
  );
  const params = [
    ...positional,
    optionsParam(className, required, optional),
  ].join(', ');
  // Positional fields seed the payload; the rest spreads over them.
  const payload =
    required.length === 0
      ? 'rest'
      : `{ ${required.map((field) => field.name).join(', ')}, ...rest }`;

  return `${jsdoc(method, required)}${name}(${params}) {
  const { token, signal, ...rest } = callOptions ?? {};
  return this.call(new ${className}(${payload}), { token, signal });
}`;
}

export function emitBotMethods(methods: IrMethod[]): string {
  const selected = methods.filter((method) => !isSkippedBotMethod(method.name));

  const imports = new Set<string>();
  for (const method of selected) {
    imports.add(method.className);
    if (method.args.length > 0) {
      imports.add(`${method.className}Options`);
    }
  }
  const methodImports = [...imports]
    .sort()
    .map((name) => `  ${name},`)
    .join('\n');

  const body = selected.map(emitMethod).join('\n\n');

  return `${HEADER}
import { ApiMethod } from './methods/api-method';
import type { CallOptions, MethodOptions } from './bot.service';
import {
${methodImports}
} from './methods';

/**
 * Generated \`bot.<method>(...)\` sugar — one wrapper per Bot API method without
 * bespoke BotService logic. Required arguments are positional, optional ones go
 * in a trailing \`callOptions\` object (which also carries \`token\`/\`signal\`).
 * BotService extends this and provides \`call\`; the command object is the layer beneath.
 */
export abstract class GeneratedBotMethods {
  protected abstract call<R>(
    method: ApiMethod<unknown, R>,
    options?: CallOptions,
  ): Promise<R>;

${body}
}
`;
}
